import React, { useEffect, useMemo, useRef, useState } from "react";
import { NavLink, useLocation } from "react-router-dom";
import { io, type Socket } from "socket.io-client";
import { Activity, Radio, ShieldCheck, ShoppingCart } from "lucide-react";
import { PageHeader } from "./components/layout/PageHeader";
import { TestInfoPanel } from "./components/testing/TestInfoPanel";

const api = async (url: string, init?: RequestInit) => {
  const response = await fetch(url, { ...init, headers: { "content-type": "application/json", "x-test-key": "testlab-control", authorization: `Bearer ${localStorage.getItem("token") || ""}`, ...init?.headers } });
  const body = response.status === 204 ? null : await response.json();
  if (!response.ok) throw new Error(body?.error || `HTTP ${response.status}`);
  return body;
};
type CartItem = { productId: number; name: string; price: number; quantity: number; inventory: number };
const readCart = (): CartItem[] => JSON.parse(localStorage.getItem("phase4-cart") || "[]");

export function Phase4Shop() {
  const path = useLocation().pathname,
    [cart, setCart] = useState<CartItem[]>(readCart),
    [products, setProducts] = useState<any[]>([]),
    [orders, setOrders] = useState<any[]>([]),
    [query, setQuery] = useState(""), [category, setCategory] = useState(""), [sort, setSort] = useState("name"),
    [message, setMessage] = useState(""), [discount, setDiscount] = useState(""), [card, setCard] = useState("4111111111111111"),
    [address, setAddress] = useState({ line1: "100 Automation Way", city: "Toronto" }), [shipping, setShipping] = useState("standard");
  const saveCart = (next: CartItem[]) => { setCart(next); localStorage.setItem("phase4-cart", JSON.stringify(next)); };
  const loadProducts = () => api(`/api/shop/products?q=${encodeURIComponent(query)}&category=${encodeURIComponent(category)}&sort=${sort}`).then((x) => setProducts(x.data)).catch((e) => setMessage(e.message));
  useEffect(() => { void loadProducts(); }, []);
  useEffect(() => { if (path.endsWith("/orders")) api("/api/shop/orders").then((x) => setOrders(x.data)).catch((e) => setMessage(e.message)); }, [path]);
  const subtotal = useMemo(() => cart.reduce((sum, item) => sum + item.price * item.quantity, 0), [cart]);
  const add = (product: any) => { const found = cart.find((item) => item.productId === product.id); saveCart(found ? cart.map((item) => item.productId === product.id ? { ...item, quantity: Math.min(item.inventory, item.quantity + 1) } : item) : [...cart, { productId: product.id, name: product.name, price: product.price, quantity: 1, inventory: product.inventory }]); setMessage(`${product.name} added to cart`); };
  const checkout = async (event: React.FormEvent) => { event.preventDefault(); setMessage(""); try { const result = await api("/api/shop/checkout", { method: "POST", body: JSON.stringify({ items: cart, cardNumber: card, shippingAddress: address, billingAddress: address, shippingMethod: shipping, discountCode: discount || undefined }) }); saveCart([]); setMessage(`Order ${result.orderId}: ${result.message}. Total $${result.total}`); } catch (error: any) { setMessage(error.message); } };
  const nav = <nav className="module-tabs"><NavLink to="/shop/products">Products</NavLink><NavLink to="/shop/cart">Cart ({cart.reduce((x, i) => x + i.quantity, 0)})</NavLink><NavLink to="/shop/checkout">Checkout</NavLink><NavLink to="/shop/orders">Orders</NavLink></nav>;
  if (path.endsWith("/cart")) return <><PageHeader icon={ShoppingCart} title="Shopping Cart" description="Practice persisted cart changes, quantity limits, removal, discounts, and exact totals." onReset={() => saveCart([])} />{nav}<div className="panel cart-list">{cart.length ? cart.map((item) => <div key={item.productId} data-testid={`cart-item-${item.productId}`}><span><strong>{item.name}</strong><small>${item.price.toFixed(2)} each</small></span><input aria-label={`Quantity for ${item.name}`} type="number" min="1" max={item.inventory} value={item.quantity} onChange={(e) => saveCart(cart.map((x) => x.productId === item.productId ? { ...x, quantity: Number(e.target.value) } : x))}/><button className="danger" onClick={() => saveCart(cart.filter((x) => x.productId !== item.productId))}>Remove</button></div>) : <p data-testid="empty-cart">Your cart is empty.</p>}<strong data-testid="cart-total">Subtotal: ${subtotal.toFixed(2)}</strong></div><TestInfoPanel name="Shopping cart" concepts="persistence, quantity, removal, stock limits, totals" endpoints="GET /api/shop/products" /></>;
  if (path.endsWith("/checkout")) return <><PageHeader icon={ShoppingCart} title="Mock Checkout" description="Exercise addresses, shipping, discount, payment success, decline, timeout, and order confirmation." onReset={() => setMessage("")} />{nav}<form className="panel form checkout-grid" onSubmit={checkout}><label>Shipping address<input data-testid="shipping-address" value={address.line1} onChange={(e) => setAddress({ ...address, line1: e.target.value })} required /></label><label>City<input value={address.city} onChange={(e) => setAddress({ ...address, city: e.target.value })} required /></label><label>Shipping method<select value={shipping} onChange={(e) => setShipping(e.target.value)}><option value="standard">Standard — $5</option><option value="express">Express — $15</option></select></label><label>Discount code<input data-testid="discount-code" value={discount} onChange={(e) => setDiscount(e.target.value)} placeholder="SAVE10" /></label><label>Mock card number<input data-testid="card-number" value={card} onChange={(e) => setCard(e.target.value)} required /></label><div className="payment-scenarios"><small>Success: 4111111111111111</small><small>Declined: 4000000000000002</small><small>Timeout: 4000000000009995</small></div><button disabled={!cart.length}>Pay ${subtotal.toFixed(2)}</button><output role="alert">{message}</output></form><TestInfoPanel name="Checkout" concepts="shipping, billing, tax, discounts, mock payments, confirmation" endpoints="POST /api/shop/checkout" /></>;
  if (path.endsWith("/orders")) return <><PageHeader icon={ShoppingCart} title="Order History" description="Verify persisted orders, status, cancellation and realtime status changes." onReset={() => location.reload()} />{nav}<div className="panel table-wrap"><table><thead><tr><th>Order</th><th>Status</th><th>Total</th><th>Date</th><th>Action</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td>#{order.id}</td><td>{order.status}</td><td>${Number(order.total).toFixed(2)}</td><td>{order.created_at}</td><td><button disabled={order.status === "DELIVERED" || order.status === "CANCELLED"} onClick={() => api(`/api/shop/orders/${order.id}/cancel`, { method: "POST" }).then(() => setOrders(orders.map((x) => x.id === order.id ? { ...x, status: "CANCELLED" } : x))).catch((e) => setMessage(e.message))}>Cancel</button></td></tr>)}</tbody></table></div><output role="alert">{message}</output><TestInfoPanel name="Order history" concepts="history, details, cancellation, status" endpoints="GET /api/shop/orders, POST /api/shop/orders/:id/cancel" /></>;
  return <><PageHeader icon={ShoppingCart} title="E-commerce Workflow" description="Practice search, filtering, sorting, stock, wishlist, product details, and cart behavior." onReset={() => { setQuery(""); setCategory(""); setSort("name"); }} />{nav}<div className="panel shop-filters"><input aria-label="Search products" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search products"/><select aria-label="Category" value={category} onChange={(e) => setCategory(e.target.value)}><option value="">All categories</option><option>Hardware</option><option>Software</option><option>Accessories</option></select><select aria-label="Sort products" value={sort} onChange={(e) => setSort(e.target.value)}><option value="name">Name</option><option value="price_asc">Price low-high</option><option value="price_desc">Price high-low</option><option value="rating">Rating</option></select><button onClick={loadProducts}>Apply</button></div><div className="cards">{products.map((product) => <article className="card product-card" key={product.id} data-testid={`shop-product-${product.id}`}><span className="eyebrow">{product.category}</span><h3>{product.name}</h3><span aria-label={`${product.rating} star rating`}>{"★".repeat(product.rating)}{"☆".repeat(5-product.rating)}</span><strong>${Number(product.price).toFixed(2)}</strong><small className={product.inventory < 5 ? "warning-text" : ""}>{product.inventory === 0 ? "Out of stock" : product.inventory < 5 ? `Only ${product.inventory} left` : `${product.inventory} in stock`}</small><div className="actions"><button disabled={!product.inventory} onClick={() => add(product)}>Add to cart</button><button className="secondary" aria-label={`Wishlist ${product.name}`} onClick={() => api(`/api/shop/wishlist/${product.id}`, { method: "POST" }).then(() => setMessage("Added to wishlist"))}>♡</button></div></article>)}</div><output role="status">{message}</output><TestInfoPanel name="Product catalog" concepts="search, category, price, rating, sorting, stock, wishlist, cart" endpoints="GET /api/shop/products, POST /api/shop/wishlist/:id" /></>;
}

export function Phase4Network() {
  const [method, setMethod] = useState("GET"), [status, setStatus] = useState(""), [config, setConfig] = useState({ delay: 0, failureRate: 0, offline: false, statusCode: "" });
  const send = () => fetch("/api/network/echo?source=playground", { method, headers: { "content-type": "application/json", authorization: `Bearer ${localStorage.getItem("token") || ""}` }, body: ["POST", "PUT", "PATCH"].includes(method) ? JSON.stringify({ message: "Phase 4 request" }) : undefined }).then(async (r) => setStatus(`${r.status}\n${await r.text()}`)).catch((e) => setStatus(e.message));
  return <><PageHeader icon={Activity} title="API & Network Playground" description="Send REST requests and deterministically simulate latency, status failures, and offline behavior." onReset={() => setStatus("")} /><div className="phase4-grid"><section className="panel"><h3>Request builder</h3><select aria-label="HTTP method" value={method} onChange={(e) => setMethod(e.target.value)}>{["GET","POST","PUT","PATCH","DELETE"].map((x) => <option key={x}>{x}</option>)}</select><button onClick={send}>Send request</button><pre role="status" data-testid="network-response">{status || "No request sent"}</pre><a href="/api/docs" target="_blank" rel="noreferrer">Swagger API documentation</a></section><section className="panel form"><h3>Network simulation</h3><label>Delay (ms)<input type="number" value={config.delay} onChange={(e) => setConfig({ ...config, delay: Number(e.target.value) })}/></label><label>Forced status<input placeholder="none" value={config.statusCode} onChange={(e) => setConfig({ ...config, statusCode: e.target.value })}/></label><label className="check"><input type="checkbox" checked={config.offline} onChange={(e) => setConfig({ ...config, offline: e.target.checked })}/>Offline mode</label><button onClick={() => api("/api/test/network", { method: "POST", body: JSON.stringify({ ...config, statusCode: config.statusCode ? Number(config.statusCode) : null }) }).then((x) => setStatus(JSON.stringify(x, null, 2)))}>Apply simulation</button></section></div><TestInfoPanel name="API and network" concepts="REST methods, status codes, latency, offline, custom headers, request IDs" endpoints="ALL /api/network/echo, POST /api/test/network, GET /api/docs" /></>;
}

export function Phase4Realtime() {
  const socket = useRef<Socket | null>(null), [connected, setConnected] = useState(false), [message, setMessage] = useState("Hello automation"), [events, setEvents] = useState<string[]>([]);
  useEffect(() => { const current = io(); socket.current = current; current.on("connect", () => setConnected(true)); current.on("disconnect", () => setConnected(false)); for (const name of ["chat", "test-event", "order-status", "counter"]) current.on(name, (data) => setEvents((items) => [`${name}: ${JSON.stringify(data)}`, ...items])); return () => { current.close(); }; }, []);
  return <><PageHeader icon={Radio} title="Real-time Automation" description="Practice connection state, chat, live orders, counters, server events, and reconnection." onReset={() => setEvents([])} /><div className="phase4-grid"><section className="panel"><h3><span className={connected ? "status-dot" : "status-dot offline"}/> {connected ? "Online" : "Offline"}</h3><input aria-label="Realtime message" value={message} onChange={(e) => setMessage(e.target.value)}/><div className="actions"><button onClick={() => socket.current?.emit("chat", { text: message })}>Send chat</button><button onClick={() => socket.current?.emit("counter")}>Update counter</button></div></section><section className="panel"><h3>Live event stream</h3><ol data-testid="realtime-events">{events.length ? events.map((event, i) => <li key={`${event}-${i}`}>{event}</li>) : <li>Waiting for events</li>}</ol></section></div><TestInfoPanel name="WebSockets" concepts="connect, disconnect, chat, live order status, counters, server events, reconnection" endpoints="WS /socket.io, POST /api/test/events" /></>;
}

export function Phase4Admin() {
  const [summary, setSummary] = useState<any>(null), [orders, setOrders] = useState<any[]>([]), [audit, setAudit] = useState<any[]>([]), [query, setQuery] = useState("");
  useEffect(() => { Promise.all([api("/api/admin/summary"), api("/api/admin/orders"), api("/api/admin/audit")]).then(([s,o,a]) => { setSummary(s); setOrders(o.data); setAudit(a.data); }); }, []);
  const shown = orders.filter((order) => `${order.id} ${order.email} ${order.status}`.toLowerCase().includes(query.toLowerCase()));
  return <><PageHeader icon={ShieldCheck} title="Admin Operations Dashboard" description="Admin-only metrics, order oversight, activity audit, filtering, and report export." onReset={() => location.reload()} /><div className="visual">{[["Users",summary?.users],["Orders",summary?.orders],["Revenue",summary ? `$${Number(summary.revenue).toFixed(2)}` : "—"],["Products",summary?.products]].map(([label,value]) => <div className="metric" key={label}><b>{label}</b><strong>{value ?? "—"}</strong></div>)}</div><div className="phase4-grid"><section className="panel table-wrap"><div className="section-heading"><h3>Orders</h3><a className="button secondary" href="/api/admin/export">Export CSV</a></div><input aria-label="Filter admin orders" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Filter orders"/><table><thead><tr><th>ID</th><th>User</th><th>Status</th><th>Total</th></tr></thead><tbody>{shown.map((o) => <tr key={o.id}><td>{o.id}</td><td>{o.email}</td><td>{o.status}</td><td>${Number(o.total).toFixed(2)}</td></tr>)}</tbody></table></section><section className="panel"><h3>Recent audit activity</h3><ol className="audit-list">{audit.slice(0,10).map((entry) => <li key={entry.id}><strong>{entry.action}</strong><small>{entry.created_at}</small></li>)}</ol></section></div><TestInfoPanel name="Admin dashboard" concepts="RBAC, metrics, order management, audit logs, filtering, export" endpoints="GET /api/admin/summary, /orders, /audit, /export" /></>;
}
